README.md
build.gradle.kts
src/main/java/com/wcc/platform/configuration/GlobalExceptionHandler.java
src/main/java/com/wcc/platform/controller/AboutController.java
src/main/resources/application.yml

Closes #22 
Screenshot -
Swagger configured on the backend code -

swagger-ui configured

---

src/main/java/com/wcc/platform/controller/FooterController.java
src/main/java/com/wcc/platform/domain/cms/ApiResourcesFile.java
src/main/java/com/wcc/platform/domain/cms/attributes/LabelLink.java
src/main/java/com/wcc/platform/domain/cms/attributes/Network.java
src/main/java/com/wcc/platform/domain/cms/pages/FooterPage.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/resources/footerPage.json
src/test/java/com/wcc/platform/controller/FooterControllerTest.java
src/test/java/com/wcc/platform/factories/TestFactories.java
src/test/java/com/wcc/platform/service/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java

Footer api with all the details 
API response -

Add footer cms api

---

src/main/resources/homePage.json

The json file was not pushed by mistake.

fix: Add missing resource for home section api

---

src/main/java/com/wcc/platform/utils/FileUtil.java

Define encode type for file read.

fix: Read json files with UTF-8

---

README.md
src/main/java/com/wcc/platform/configuration/ObjectMapperConfig.java
src/main/java/com/wcc/platform/controller/MentorshipController.java
src/main/java/com/wcc/platform/domain/cms/ApiResourcesFile.java
src/main/java/com/wcc/platform/domain/cms/attributes/PageSection.java
src/main/java/com/wcc/platform/domain/cms/pages/mentorship/FeedbackItem.java
src/main/java/com/wcc/platform/domain/cms/pages/mentorship/FeedbackSection.java
src/main/java/com/wcc/platform/domain/cms/pages/mentorship/MentorshipPage.java
src/main/java/com/wcc/platform/service/MentorshipService.java
src/main/resources/mentorshipPage.json
src/test/java/com/wcc/platform/controller/MentorshipControllerTest.java
src/test/java/com/wcc/platform/factories/TestFactories.java
src/test/java/com/wcc/platform/factories/TestMentorshipFactories.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java
src/test/java/com/wcc/platform/service/MentorshipServiceTest.java
src/test/resources/mentorshipPage.json

feat: Create mentorship overview API

---

src/main/java/com/wcc/platform/domain/cms/ApiResourcesFile.java

Fix complication problems with enum class.

fix: Solve wrong merge conflict

---

.github/CODEOWNERS

add backend team as code owner

doc: add code owners

---

README.md
build.gradle.kts

Closes [#9](https://github.com/Women-Coding-Community/wcc-backend/issues/9)
SonarQube to be set-up locally to perform the analysis on the code.
This will help us to build clean code ( best practices)
1. Added the steps how to set-up the sonarQube instance locally and run it.
2. Add comamnd how to perform the analysis.

Add sonarQube analysis

---

src/main/java/com/wcc/platform/controller/EventController.java
src/main/java/com/wcc/platform/domain/cms/ApiResourcesFile.java
src/main/java/com/wcc/platform/domain/cms/attributes/EventResource.java
src/main/java/com/wcc/platform/domain/cms/attributes/EventType.java
src/main/java/com/wcc/platform/domain/cms/attributes/HeroSection.java
src/main/java/com/wcc/platform/domain/cms/attributes/ProgramType.java
src/main/java/com/wcc/platform/domain/cms/pages/EventsPage.java
src/main/java/com/wcc/platform/domain/platform/Event.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/resources/eventsPage.json
src/test/java/com/wcc/platform/controller/EventControllerTest.java
src/test/java/com/wcc/platform/factories/SetupEventFactories.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java

This reverts commit 66c8b0753a0c18b3baba409cb0cd832179bba308.

feat: Events Page 

---

src/main/java/com/wcc/platform/configuration/OpenApiConfig.java
src/main/java/com/wcc/platform/configuration/WebConfig.java
src/main/java/com/wcc/platform/domain/platform/config/PlatformServers.java

Enable dev server: https://wcc-backend.fly.dev/swagger-ui/index.html to execute the api's.  
Close #70

feat: Enable Swagger to access dev server

---

.gitignore
.sonarlint/connectedMode.json

Add sonar cloud config to bind locally with intelliJ

chore: SonarCloud databind setup local

---

.gitignore
integration-test/README.md
integration-test/global-setup.ts
integration-test/package.json
integration-test/playwright.config.ts
integration-test/tests/ApiHost.ts
integration-test/tests/cms/footer.test.ts
integration-test/tests/cms/landingpage.test.ts
integration-test/tests/envVariables.ts
integration-test/tests/openapi/openapi.test.ts
integration-test/tsconfig.json

Setup Playwright to create integration tests
Closes #126

test: Setup Playwright for integration test

---

src/main/java/com/wcc/platform/controller/AboutController.java
src/main/java/com/wcc/platform/controller/DefaultController.java
src/main/java/com/wcc/platform/controller/EventController.java
src/main/java/com/wcc/platform/controller/MemberController.java
src/main/java/com/wcc/platform/controller/MentorshipController.java
src/main/java/com/wcc/platform/controller/ProgrammeController.java
src/main/java/com/wcc/platform/controller/platform/PageController.java
src/main/java/com/wcc/platform/controller/platform/ResourceContentController.java
src/main/resources/application.yml

resolve #127 
* Sort Apis ASC
* Sort Method ASC
* Re-organize Api's in Pages and Platform

feat: Adjust Swagger UI

---

build.gradle.kts
src/main/java/com/wcc/platform/configuration/GlobalExceptionHandler.java
src/main/java/com/wcc/platform/controller/EventController.java
src/main/java/com/wcc/platform/utils/PaginationUtil.java
src/test/java/com/wcc/platform/controller/EventControllerTest.java
src/test/java/com/wcc/platform/domain/platform/EventTest.java

Add dependency, test spring validator

---

integration-test/tests/cms/mentorshipoverview.test.ts

Added one CMS file mentorshipoverview.test.ts
Passed Test Screen shot.

Integration test mentorship overview

---

src/main/java/com/wcc/platform/configuration/RepositoryConfig.java
src/main/java/com/wcc/platform/controller/platform/PageController.java
src/main/java/com/wcc/platform/domain/cms/pages/LandingPage.java
src/main/java/com/wcc/platform/domain/exceptions/PlatformInternalException.java
src/main/java/com/wcc/platform/repository/PageRepository.java
src/main/java/com/wcc/platform/repository/surrealdb/SurrealDbPageRepository.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/java/com/wcc/platform/service/PlatformService.java
src/test/java/com/wcc/platform/repository/surrealdb/SurrealDbPageRepositoryTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java

That is a problem with saving the page, and because of that I am going to revert
Reverts Women-Coding-Community/wcc-backend#129

Revert "feat: Adjust repository to create single table for pages"

---

src/test/java/com/wcc/platform/integrationtests/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java

Relevant to: [#148](https://github.com/Women-Coding-Community/wcc-backend/issues/115)
Add missing tests.
Add service integration test.

feat: Create GET About Page test

---

integration-test/tests/cms/collaborators.test.ts
integration-test/tests/cms/mentorshipoverview.test.ts

Added one CMS file for Integration test collaborators
Added passed Screen short

Integration test collaborators

---

integration-test/playwright.config.ts
integration-test/tests/cms/codeofconduct.test.ts
integration-test/tests/cms/footer.test.ts
src/main/java/com/wcc/platform/configuration/RepositoryConfig.java
src/main/java/com/wcc/platform/controller/platform/PageController.java
src/main/java/com/wcc/platform/controller/platform/ResourceContentController.java
src/main/java/com/wcc/platform/domain/cms/pages/FooterPage.java
src/main/java/com/wcc/platform/domain/cms/pages/LandingPage.java
src/main/java/com/wcc/platform/domain/exceptions/PlatformInternalException.java
src/main/java/com/wcc/platform/repository/CrudRepository.java
src/main/java/com/wcc/platform/repository/PageRepository.java
src/main/java/com/wcc/platform/repository/surrealdb/SurrealDbPageRepository.java
src/main/java/com/wcc/platform/repository/surrealdb/SurrealDbResourceRepository.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/java/com/wcc/platform/service/PlatformService.java
src/test/java/com/wcc/platform/repository/surrealdb/SurrealDbPageRepositoryTest.java
src/test/java/com/wcc/platform/repository/surrealdb/SurrealDbResourceRepositoryTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java
src/test/java/com/wcc/platform/service/PlatformServiceTest.java

As part of POC using SurrealDB, we decided to create single table instead one for each page. 
The pages should have single table with content as string
The content will be json string and the service should take care of serialization and de-serialization
Also created Delete endpoint and Get all pages
resolve #131

feat: Adjust repository to create single table for pages

---

src/main/java/com/wcc/platform/controller/AboutController.java
src/main/java/com/wcc/platform/domain/cms/pages/CollaboratorPage.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/resources/collaboratorPage.json
src/test/java/com/wcc/platform/controller/AboutControllerTest.java
src/test/java/com/wcc/platform/factories/SetupFactories.java
src/test/java/com/wcc/platform/integrationtests/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java
src/test/resources/collaboratorPage.json

this task adds pagination to the collaborators page
The screenshot shows the result of the code change when running the application locally
refers to #30 feat: Upgrade Collaborators rest api - add pagination

feat: Update-collaborators: add pagination

---

src/main/java/com/wcc/platform/controller/platform/PageController.java
src/main/java/com/wcc/platform/domain/cms/pages/TeamPage.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/java/com/wcc/platform/service/PageService.java
src/main/resources/application-docker.yml
src/main/resources/application.yml
src/main/resources/footerPage.json
src/test/java/com/wcc/platform/factories/SetupFactories.java
src/test/java/com/wcc/platform/integrationtests/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java
src/test/resources/teamPage.json

Instead of read from file Json file we are now using database and can insert/select data from database, as it is done in Landing Page and in Footer
Closes #173 

feat: Use database for TEAM Page

---

integration-test/tests/cms/footer.test.ts
integration-test/utils/datafactory/footer.data.ts
integration-test/utils/datafactory/schemas/footer.schema.ts
integration-test/utils/datafactory/schemas/link.schema.ts

- Updated expected JSON schema for Footer API
- Updated expected JSON response for Footer API
- Improved Schema Validation in order to have failed test case in case of schema validation failing 
https://github.com/Women-Coding-Community/wcc-backend/issues/181

Maintained Footer API Test Case and Updated schema validation

---

build.gradle.kts
src/main/java/com/wcc/platform/controller/DefaultController.java
src/main/java/com/wcc/platform/controller/platform/PageController.java
src/main/java/com/wcc/platform/domain/cms/PageType.java
src/main/java/com/wcc/platform/domain/cms/pages/FooterSection.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/java/com/wcc/platform/service/PageService.java
src/main/resources/teamPage.json
src/test/java/com/wcc/platform/controller/DefaultControllerTest.java
src/test/java/com/wcc/platform/factories/SetupFactories.java
src/test/java/com/wcc/platform/integrationtests/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/integrationtests/SurrealDbIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java

Rename FooterPage to FooterSection

refactor: Rename FooterPage to FooterSection

---

integration-test/tests/cms/about.us.test.ts
integration-test/utils/datafactory/footer.data.ts
integration-test/utils/datafactory/schemas/about.schema.ts
integration-test/utils/datafactory/schemas/contact.schema.ts
integration-test/utils/datafactory/schemas/custom.style.schema.ts
integration-test/utils/datafactory/schemas/page.schema.ts
integration-test/utils/datafactory/schemas/social.network.schema.ts

- Introduced About Us API response schema
- Separated small schemas to be reused in the future
- Maintained footer test case 
- Improved Footer API Response Schema 
Closes https://github.com/Women-Coding-Community/wcc-backend/issues/202

API Test: About Us API Test Case Implementation

---

integration-test/tests/cms/collaborators.test.ts
integration-test/utils/datafactory/schemas/collaborators.schema.ts
integration-test/utils/datafactory/schemas/leadershipmember.schema.ts
integration-test/utils/datafactory/schemas/member.schema.ts
integration-test/utils/datafactory/schemas/pagination.schema.ts

- created schema for collaborators API
- abstracted small schemas
Closes https://github.com/Women-Coding-Community/wcc-backend/issues/151

API Test: Added Collaborators API tests with schema validation

---

integration-test/tests/cms/events.test.ts
integration-test/utils/datafactory/schemas/contact.schema.ts
integration-test/utils/datafactory/schemas/event.schema.ts
integration-test/utils/datafactory/schemas/events.schema.ts
integration-test/utils/datafactory/schemas/hero.section.schema.ts
integration-test/utils/datafactory/schemas/member.schema.ts

- added schema for Events 
- abstracted separate schemas
- created basic test case for events API
Close #211 

Add events test case with schema validation

---

integration-test/tests/cms/codeofconduct.test.ts
integration-test/utils/datafactory/schemas/codeofconduct.schema.ts

Added one schema file 'codeofconduct.schema.ts'
corrected codofconduct.test.ts.

 Integration test code of conduct

---

integration-test/tests/cms/mentorshipoverview.test.ts
integration-test/utils/datafactory/schemas/feedback.schema.ts
integration-test/utils/datafactory/schemas/mentorship.schema.ts
integration-test/utils/datafactory/schemas/pagesection.schema.ts

Added "pagesection.schema.ts"
Corrected "mentorshipoverviewtest.ts"
Added "feedback.schema.ts
Added "mentorship.schema.ts"

mentorship overview schema validation

---

src/main/resources/application.yml

Adjusted security token for local environment 

Fix local security key

---

integration-test/.env.example
integration-test/playwright.config.ts

- Added extra header to authorise requests 
- Updated .env.example with the new env variable `API_KEY`
Close https://github.com/Women-Coding-Community/wcc-backend/issues/217

API Tests: Added extra header to authorize requests in test cases

---

fly.toml
src/main/resources/application.yml

Trying to deploy automatic dev environment on merge to main branch. Also keep the dev up 

chore: Keep dev up

---

integration-test/playwright.config.ts
integration-test/utils/datafactory/schemas/about.schema.ts
integration-test/utils/datafactory/schemas/codeofconduct.schema.ts
integration-test/utils/datafactory/schemas/collaborators.schema.ts
integration-test/utils/datafactory/schemas/events.schema.ts
integration-test/utils/datafactory/schemas/hero.section.schema.ts
integration-test/utils/datafactory/schemas/mentorship.schema.ts
integration-test/utils/datafactory/schemas/team.schema.ts

1. `heroSection` property included into following JSON schemas:
- AboutUsPage.java
- CodeOfConductPage.java
- CollaboratorPage.java
- EventsPage.java
- MentorshipPage.java
- TeamPage.java
2. Refactored a few schemas
Close https://github.com/Women-Coding-Community/wcc-backend/issues/218

API Tests: Updated `heroSection` property for multiple requests

---

src/main/java/com/wcc/platform/service/PageService.java
src/test/java/com/wcc/platform/integrationtests/PageServiceIntegrationTest.java
src/test/java/com/wcc/platform/integrationtests/SurrealDbIntegrationTest.java
src/test/java/com/wcc/platform/service/PageServiceTest.java

- Override page content id with the same as PageType id, to avoid conflict with page content and page types.
- Before update check if page exist and if does not exist throw exception

feat: Override content id to be PageType id

---

integration-test/tests/cms/eventsfilters.test.ts
integration-test/utils/datafactory/schemas/eventsfilters.schema.ts

Added two files for events filters
eventsfilters.schema.ts
eventsfilters.test.ts
passed screen shots 
Checked for the negative scenarios too and working as expected. 

API integration events filters

---

.github/workflows/playwright-tests.yml
.gitignore
integration-test/package-lock.json
integration-test/playwright.config.ts

Created separate file to describe the workflow and trigger playwright API test in midnight
Closes #267 

GitHub Actions to trigger integration tests every day by midnight

---

integration-test/tests/cms/landing.test.ts
integration-test/utils/datafactory/schemas/landing.page.schema.ts
integration-test/utils/datafactory/schemas/link.schema.ts
integration-test/utils/datafactory/schemas/programme.item.schema.ts
integration-test/utils/datafactory/schemas/section.event.schema.ts
integration-test/utils/datafactory/schemas/section.programme.schema.ts

- Added integration test for Landing Page
- Added schema for landing page response
- Updated Link Schema 
Close #248 

API Test: Added integration test for landing page

---

src/main/java/com/wcc/platform/controller/MentorshipController.java
src/main/java/com/wcc/platform/domain/cms/PageType.java
src/main/java/com/wcc/platform/domain/cms/attributes/FaqItem.java
src/main/java/com/wcc/platform/domain/cms/pages/mentorship/MentorshipFaqPage.java
src/main/java/com/wcc/platform/service/MentorshipService.java
src/main/resources/mentorshipFaqPage.json
src/test/java/com/wcc/platform/controller/MentorshipControllerTest.java
src/test/java/com/wcc/platform/factories/SetupMentorshipFactories.java
src/test/java/com/wcc/platform/service/MentorshipServiceTest.java
src/test/resources/mentorshipFaqPage.json

Mentorship FAQ page 
- Describe your changes in detail.
- Why is this change required?
- What problem does it solve?
- Add Notes if anything is left unclear or not completed
[#74]

mentorship faq page

---

src/main/java/com/wcc/platform/controller/MentorshipController.java
src/main/java/com/wcc/platform/domain/cms/PageType.java
src/main/java/com/wcc/platform/domain/cms/pages/mentorship/MentorshipCodeOfConductPage.java
src/main/java/com/wcc/platform/service/MentorshipService.java
src/main/resources/mentorshipConductPage.json
src/test/java/com/wcc/platform/controller/MentorshipControllerTest.java
src/test/java/com/wcc/platform/factories/SetupMentorshipFactories.java
src/test/java/com/wcc/platform/service/MentorshipServiceTest.java
src/test/resources/mentorshipConductPage.json

This is to add the mentorship code of conduct pages
Closes #66
New endpoint for the mentorship code of conduct
Mentorship code of conduct response

Code of conduct mentorship

---

integration-test/tests/cms/mentorshipfaq.test.ts
integration-test/utils/datafactory/schemas/listsectionfaqitem.schema.ts
integration-test/utils/datafactory/schemas/mentorshipfaq.schema.ts

- Added three filesmentorshipfaq.test.ts file
- Added listsectionfaqitem.schema.ts
- Added mentorshipfaqschema.ts

 API integration test mentorship faq

---

integration-test/tests/cms/partners.test.ts
integration-test/utils/datafactory/schemas/items.schema.ts
integration-test/utils/datafactory/schemas/listsectionpartner.schema.ts
integration-test/utils/datafactory/schemas/partner.schema.ts
integration-test/utils/datafactory/schemas/partners.schema.ts

Added three Schema files - Items.schema.ts. ,listsectionpartner.schema.ts,partners.schema.ts
Added one CMS test file - partners.test.ts
- Describe your changes in detail.
- Why is this change required?
- What problem does it solve?
- Add Notes if anything is left unclear or not completed
https://github.com/Women-Coding-Community/wcc-backend/issues/314

Integration API test partners

---

integration-test/tests/cms/mentorshipcodeofconduct.test.ts

Added pre conditions for Mentorship code of conduct 
Added put, post and delete preconditions test
Closes https://github.com/Women-Coding-Community/wcc-backend/issues/307

Adding pre conditions for mentorship code of conduct

---

src/main/resources/samples/MeetOurMentors_template.json
src/main/resources/samples/meetOurMentorsReviewsSection_template.json
src/main/resources/samples/mentee_template.json

- Added `mentee_template.json` under `main/resources/samples`
- Added `MeetOurMentors_template.json` under `main/resources/samples`
- These files can be used as a reference for creation of json data files and Figma UX layout for Mentorship pages
PLEASE NOTE:
- ```"mentors": [ "mentor1", "mentor2" ]``` represents the chosen names from Mentors dropdown list
- ```"type": "DEFAULT_LINK",  "link": "https://xyz.com/"``` represents link to CV
- ```"languages": [ "Language1", "Language2","Language3" ]``` has been added to represent the languages known by mentee
#76 
#77 
#279

Added mentee_template.json and MeetOurMentors_template.json sample files

---

README.md
src/main/resources/interviewPreparationPage.json

Describe your changes in detail.
- Add JSON page for the Interview Preparation Programme
Why is this change required?
- Create and Test API for the InterviewPreparationPage.json file (resources)
What problem does it solve?
- Check the Page Response
Add Notes if anything is left unclear or not completed
- The page might still need more data to be complete
Closes: #57 

Add JSON Page to Interview Preparation Programme 

---

src/main/java/com/wcc/platform/domain/exceptions/ContentNotFoundException.java
src/main/java/com/wcc/platform/repository/CrudRepository.java
src/main/java/com/wcc/platform/repository/PageRepository.java
src/main/java/com/wcc/platform/service/CmsService.java
src/main/java/com/wcc/platform/service/EventService.java
src/main/java/com/wcc/platform/service/MentorshipService.java
src/main/java/com/wcc/platform/service/ProgrammeService.java
src/main/resources/footerPage.json
src/test/java/com/wcc/platform/integrationtests/CmsServiceIntegrationTest.java
src/test/java/com/wcc/platform/integrationtests/ProgramControllerIntegrationTest.java
src/test/java/com/wcc/platform/service/CmsServiceTest.java
src/test/java/com/wcc/platform/service/EventServiceTest.java
src/test/java/com/wcc/platform/service/MentorshipServiceTest.java

We are having problems with the database been empty and as temporary solution we are returning the json resources files as fallback to unblock frontend team. 

Create fallback for pages from JSON

---

build.gradle.kts
src/main/java/com/wcc/platform/configuration/OpenApiConfig.java
src/main/resources/application.yml
src/main/resources/bookClubPage.json

Enable Actuator Endpoint to give extra visibility in our Dev environment. 

Enable Actuator Endpoint

---

src/main/resources/db/migration/V2__create_members_data_model.sql

Data model for the members data

initial commit data model

---

src/main/java/com/wcc/platform/controller/MemberController.java
src/main/java/com/wcc/platform/domain/platform/Member.java
src/main/java/com/wcc/platform/repository/MembersRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresCountryRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresImageRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresMemberImageRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresMemberMemberTypeRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresMemberRepository.java
src/main/java/com/wcc/platform/repository/postgres/PostgresSocialNetworkRepository.java
src/main/java/com/wcc/platform/repository/postgres/component/MemberMapper.java
src/main/java/com/wcc/platform/service/PlatformService.java
src/main/resources/db/migration/V5__create_relation_members_data_model.sql
src/test/java/com/wcc/platform/repository/postgres/PostgresMemberRepositoryTest.java
src/test/java/com/wcc/platform/repository/postgres/component/MemberMapperTest.java
src/test/java/com/wcc/platform/service/PlatformServiceTest.java

This change is to leverage the members data model and PostgresDB to store the Memebers data and fetch the members data via the existing APIs.
[#366](https://github.com/Women-Coding-Community/wcc-backend/issues/366)
GET API - 
POST API - 
PUT API -
DB - 
Members Table -
Member_MembersType

Members get api

---

docs/google_drive_setup.md
src/main/java/com/wcc/platform/repository/file/LocalFileStorageRepository.java
src/main/java/com/wcc/platform/repository/googledrive/GoogleDriveRepository.java
src/main/java/com/wcc/platform/repository/local/LocalFileStorageRepository.java
src/main/resources/application.yml
src/test/java/com/wcc/platform/controller/MentorshipControllerTest.java
src/test/java/com/wcc/platform/domain/platform/LongTermTimelineEventTest.java
src/test/java/com/wcc/platform/repository/local/LocalFileStorageRepositoryTest.java
src/test/java/com/wcc/platform/service/MentorshipServiceTest.java
src/testInt/java/com/wcc/platform/repository/local/LocalFileStorageRepositoryIntegrationTest.java

In order to simplify local development are creating local storage and developers could use it instead of setup GoogleDrive. 
In this case only if is necessary to test with GoogleDrive developers can change the configuration.

Support LocalStorage and GoogleDrive

---

src/main/java/com/wcc/platform/repository/FileStorageRepository.java
src/main/java/com/wcc/platform/repository/googledrive/GoogleDriveFileStorageRepository.java
src/test/java/com/wcc/platform/repository/googledrive/GoogleDriveFileStorageRepositoryTest.java
src/testInt/java/com/wcc/platform/config/TestGoogleDriveRepositoryConfig.java
src/testInt/java/com/wcc/platform/repository/googledrive/GoogleDriveFileStorageRepositoryIntegrationTest.java
src/testInt/java/com/wcc/platform/repository/googledrive/GoogleDriveFileStorageRepositoryPerformanceTest.java

GoogleDriveFileStorageRepository is implementing FileStorageRepository and the name was not following the code convention. This change simplify and makes easier to maintain.

refactor: Rename Google Drive Repository to align with interface

---

.github/workflows/fly-deploy.yml
src/main/resources/application-flyio.yml

After merge changes to main branch, it is possible to deploy changes to fly.io dev env. In order to make this happen these were the necessary changes:
- Add flyio profile 
- Create workflow for Github actions to deploy after merge

chore: Enable Continues Integration for dev

---

.github/workflows/fly-deploy.yml

- Create jar before to try to deploy application
- Support manual execution of the deployment

chore: Enable Continues Integration for dev Step-2

---

.github/workflows/ci.yml
.github/workflows/fly-deploy.yml

Add in the deployment action the necessary steps to deploy the application to dev env
- Run only 1 job

chore: Enable Continues Integration for dev Step-4

---

.github/workflows/ci.yml
.github/workflows/sonar.yml

Enable sonar checks on PR and after merge to main branch

Create github action for sonar

---

.github/workflows/sonar.yml
src/main/java/com/wcc/platform/repository/file/LocalFileStorageRepository.java
src/test/java/com/wcc/platform/repository/file/FileMemberRepositoryTest.java
src/test/java/com/wcc/platform/repository/file/FilePageRepositoryTest.java
src/test/java/com/wcc/platform/repository/file/FileRepositoryExceptionTest.java
src/test/java/com/wcc/platform/repository/local/LocalFileStorageRepositoryTest.java

Improve code coverage
